# Generated by Django 5.2.7 on 2025-12-02 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('diet_type', models.CharField(choices=[('none', 'No Restriction'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('halal', 'Halal'), ('kosher', 'Kosher')], default='none', max_length=20)),
                ('allergies', models.TextField(blank=True, help_text='Comma-separated list of allergies (e.g., peanuts, shellfish, dairy)')),
                ('favorite_cuisines', models.TextField(blank=True, help_text='Comma-separated list of favorite cuisines (e.g., Italian, Mexican, Chinese)')),
                ('daily_calorie_goal', models.IntegerField(blank=True, null=True)),
                ('protein_goal', models.IntegerField(blank=True, help_text='grams', null=True)),
                ('carbs_goal', models.IntegerField(blank=True, help_text='grams', null=True)),
                ('fat_goal', models.IntegerField(blank=True, help_text='grams', null=True)),
                ('preferred_delivery_app', models.CharField(choices=[('ubereats', 'Uber Eats'), ('doordash', 'DoorDash'), ('grubhub', 'Grubhub')], default='ubereats', max_length=20)),
                ('max_distance_miles', models.FloatField(default=5.0, help_text='Maximum distance for restaurants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
